"""empty message

Revision ID: 804ce544203d
Revises: f2d154c7bc55
Create Date: 2023-06-01 11:36:35.436792

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "804ce544203d"
down_revision = "f2d154c7bc55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("icon_name", sa.String(), nullable=True))
    op.add_column("categories", sa.Column("icon_color", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "icon_color")
    op.drop_column("categories", "icon_name")
    # ### end Alembic commands ###
