"""empty message

Revision ID: 8db0b3c70d3d
Revises: 0c6eed52399f
Create Date: 2023-06-11 17:45:07.399501

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8db0b3c70d3d"
down_revision = "0c6eed52399f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("limit", sa.Integer(), nullable=True),
        sa.Column("date_range", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("limits")
    # ### end Alembic commands ###
