"""empty message

Revision ID: f2d154c7bc55
Revises: 725589cc0adb
Create Date: 2023-05-17 14:49:41.201539

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f2d154c7bc55"
down_revision = "725589cc0adb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "type")
    # ### end Alembic commands ###
