set shell := ["sh", "-c"]

set dotenv-load := true

makemigrations:
    alembic revision --autogenerate

migrate:
    alembic upgrade head

tests:
    pytest --cov src ../../tests/auth

ci-tests:
    uv run pytest --cov src ../../tests/auth
