set shell := ["sh", "-c"]

set dotenv-required
set dotenv-load := true

makemigrations:
    alembic revision --autogenerate

migrate:
    alembic upgrade head

tests:
    pytest --cov src ../../tests/auth --module auth
