"""change users table

Revision ID: 14d9cdbdf029
Revises: f1c4a04700d3
Create Date: 2024-02-15 15:28:12.592583

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14d9cdbdf029"
down_revision: Union[str, None] = "f1c4a04700d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("auth_id", sa.String(), nullable=False))
    op.drop_index("ix_users_email", table_name="users")
    op.create_index(op.f("ix_users_auth_id"), "users", ["auth_id"], unique=True)
    op.drop_column("users", "email")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("users", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_users_auth_id"), table_name="users")
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.drop_column("users", "auth_id")
    # ### end Alembic commands ###
