"""category_icons

Revision ID: c42c96be152a
Revises: a1d7fb181137
Create Date: 2024-03-25 18:00:45.682549

"""
import json
from importlib import resources
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import select

from costy.infrastructure.db.main import get_metadata
from costy.infrastructure.db.tables import create_tables

# revision identifiers, used by Alembic.
revision: str = 'c42c96be152a'
down_revision: Union[str, None] = 'a1d7fb181137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_icons',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('icon_color', sa.String(), nullable=True),
    sa.Column('icon_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.UniqueConstraint('category_id')
    )
    # ### end Alembic commands ###

    with open(str(resources.files("costy.infrastructure.db") / "_default_categories.json")) as f:
        data = json.load(f)

    data = {item["name"]: item for item in data}

    conn = op.get_bind()
    metadata = get_metadata()
    tables = create_tables(metadata)

    categories = conn.execute(
        select(tables['categories'].c.name, tables['categories'].c.id)
        .where(tables['categories'].c.kind == "general")
    )

    op.bulk_insert(
        tables['category_icons'],
        [
            {
                "category_id": category_id,
                "icon_color": data[category_name]["icon_color"],
                "icon_name": data[category_name]["icon_name"]
            }
            for category_name, category_id in categories
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_icons')
    # ### end Alembic commands ###
