"""empty message

Revision ID: f88fa6aa2f4e
Revises: 8f0d001e35c6
Create Date: 2024-03-24 22:41:01.554640

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f88fa6aa2f4e'
down_revision: Union[str, None] = '8f0d001e35c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_mcc',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('mcc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], )
    )
    op.drop_column('categories', 'mcc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('mcc', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('category_mcc')
    # ### end Alembic commands ###
